sound_effects:
  command_received: sounds/command.wav
  shutdown: sounds/shutdown.wav
  startup: sounds/startup.wav
voice_rate: 150
voice_volume: 0.9
web_search:
  default_engine: google
  search_urls:
    google: https://www.google.com/search?q={}
    technical: https://engineering.stackexchange.com/search?q={}
workshop_mode:
  alert_cpu_threshold: 80
  alert_memory_threshold: 85
  auto_monitor: true
  monitoring_interval: 60
social_media:
  trending_cache_duration: 300
  default_location: worldwide
news_api:
  api_key: ""  # Add your API key here
  default_country: us
  headlines_count: 5
memory:
  auto_save: true
  max_conversations: 100
  conversation_expiry_days: 30
